# Generated by Django 5.2.1 on 2025-05-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire',
            name='localisation_latitude',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='localisation_longitude',
        ),
        migrations.AddField(
            model_name='prestataire',
            name='etablissement',
            field=models.CharField(default='saaba', max_length=255, verbose_name='Établissement principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestataire',
            name='zone_couverture_rayon',
            field=models.FloatField(blank=True, null=True, verbose_name='Rayon de couverture (km)'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
