# Generated by Django 5.2.1 on 2025-06-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prestataire_prenom_alter_prestataire_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
