# Generated by Django 5.2.1 on 2025-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_prestataire_localisation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5),
        ),
    ]
