# Generated by Django 5.2.1 on 2025-06-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prestataire_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='zone_couverture',
            field=models.CharField(blank=True, default='Ouagadougou', max_length=200, null=True),
        ),
    ]
