# Generated by Django 5.2.1 on 2025-06-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prestataire_zone_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
